
const K="mealplan.pwa.v1";
const D={recipes:[],plan:[],pantry:[],checked:{},prefs:{days:5,servings:4,forbidden:["Champignons","Witloof"],quick:30}};
let db=load(),tab="planning";
function load(){try{return {...structuredClone(D),...JSON.parse(localStorage.getItem(K)||"{}")}}catch{return structuredClone(D)}}
function save(){localStorage.setItem(K,JSON.stringify(db));render()}
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const id=()=>crypto.randomUUID(), nl=d=>new Intl.DateTimeFormat("nl-BE",{weekday:"long",day:"numeric",month:"long"}).format(new Date(d));
const qty=n=>Number.isInteger(n)?n:String(Math.round(n*10)/10).replace(".",",");
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
function render(){const names={planning:"Planning",recipes:"Recepten",list:"Lijst",ideas:"Ideeën",settings:"Instellingen"};$("#title").textContent=names[tab];$("#app").innerHTML=({planning,recipes,list,ideas,settings}[tab])();bind()}
function planning(){
 let h=`<section><h2>Planning maken</h2><div class=row><label>Dagen<input id=days type=number min=1 max=14 value="${db.prefs.days}"></label><label>Personen<input id=serv type=number min=1 max=6 value="${db.prefs.servings}"></label></div><button id=manual class=primary>Stel planning manueel samen</button></section>`;
 if(!db.plan.length)return h+`<section class=muted>Nog geen planning.</section>`;
 h+=`<section><h2>Huidige planning</h2>${db.plan.sort((a,b)=>a.date.localeCompare(b.date)).map(p=>{let r=db.recipes.find(x=>x.id===p.recipeId);return `<div class=day><b>${esc(nl(p.date))}</b><br>${esc(r?.name||"Onbekend")} <span class=pill>${p.servings} p.</span></div>`}).join("")}<button id=share>Deel volledige planning</button> <button id=clear class=danger>Verwijder planning</button></section>`;return h}
function recipes(){return `<section><div class=row><button id=newRecipe class=primary>+ Nieuw recept</button><button id=importRecipe>Importeer JSON</button></div></section><section>${db.recipes.length?db.recipes.map(r=>`<div class=recipe data-id="${r.id}"><b>${esc(r.name)}</b><div class=muted>${r.servings} personen • ${r.ingredients.length} ingrediënten</div><button class=edit>Bewerk</button> <button class=del>Verwijder</button></div>`).join(""):`<span class=muted>Nog geen recepten.</span>`}</section>`}
function aggregate(){let m={};for(const p of db.plan){let r=db.recipes.find(x=>x.id===p.recipeId);if(!r)continue;for(const x of r.ingredients){let key=(x.name+"|"+x.unit).toLowerCase(),f=p.servings/(r.servings||1);m[key]??={name:x.name,unit:x.unit,q:0,days:[]};m[key].q+=Number(x.quantity||0)*f;m[key].days.push(nl(p.date))}}return Object.values(m)}
function list(){let a=aggregate();return `<section><h2>Boodschappen</h2>${a.map(x=>`<div class=shop><input type=checkbox data-key="${esc(x.name)}" ${db.checked[x.name]?"checked":""}><div><b>${esc(x.name)}</b> — ${qty(x.q)} ${esc(x.unit)}<div class=muted>${esc([...new Set(x.days)].join(", "))}</div></div></div>`).join("")||'<span class=muted>Maak eerst een planning.</span>'}<br><button id=shareShop>Deel boodschappenlijst</button></section><section><h2>In huis</h2><div class=row><input id=pantryName placeholder="Ingrediënt"><button id=addPantry>Voeg toe</button></div>${db.pantry.map((x,i)=>`<div class=recipe>${esc(x)} <button data-pi="${i}" class=pantryDel>×</button></div>`).join("")}</section>`}
const ideaNames=["Kip teriyaki met rijst","Thaise rode curry","Pasta pomodoro","Citroen-parmezaan pasta","Mexicaanse fajita's","Griekse kip met couscous","Zalm met aardappelen en boontjes","Vegetarische pesto pasta","Gochujang kip met rijst","Snelle paprika-kip pan"];
function ideas(){let missing=ideaNames.filter(n=>!db.recipes.some(r=>r.name===n));let n=missing[Math.floor(Math.random()*missing.length)]||"Je hebt alle lokale ideeën opgeslagen.";return `<section><h2>Inspiratie</h2><div style="font-size:25px;font-weight:700;padding:35px 5px">${esc(n)}</div><div class=row><button id=skip>✕ Volgende</button><button id=saveIdea class=primary data-name="${esc(n)}">✓ Bewaar</button></div><p class=muted>Deze versie werkt volledig lokaal en zonder API.</p></section>`}
function settings(){return `<section><h2>Voorkeuren</h2><label>Standaard dagen<input id=pd type=number min=1 max=14 value="${db.prefs.days}"></label><label>Standaard personen<input id=ps type=number min=1 max=6 value="${db.prefs.servings}"></label><label>Niet gebruiken<input id=pf value="${esc(db.prefs.forbidden.join(", "))}"></label><button id=savePrefs>Bewaar voorkeuren</button></section><section><h2>Back-up</h2><button id=backup class=primary>Exporteer volledige back-up</button> <label class=btn>Importeer back-up<input id=restore type=file accept=".json,application/json" hidden></label><p class=muted>Bewaar geregeld een JSON-back-up in Bestanden of iCloud Drive. Foto's worden mee opgenomen.</p></section><section><h2>Installatie</h2><p class=muted>Open deze website in Safari → Deel → Zet op beginscherm → Open als webapp.</p></section>`}
function bind(){
 if($("#manual"))$("#manual").onclick=manualPlan;if($("#clear"))$("#clear").onclick=()=>{db.plan=[];save()};
 if($("#newRecipe"))$("#newRecipe").onclick=()=>editRecipe();document.querySelectorAll(".edit").forEach(b=>b.onclick=()=>editRecipe(b.parentElement.dataset.id));document.querySelectorAll(".del").forEach(b=>b.onclick=()=>{db.recipes=db.recipes.filter(r=>r.id!==b.parentElement.dataset.id);save()});
 document.querySelectorAll(".shop input").forEach(x=>x.onchange=()=>{db.checked[x.dataset.key]=x.checked;localStorage.setItem(K,JSON.stringify(db))});
 if($("#addPantry"))$("#addPantry").onclick=()=>{let v=$("#pantryName").value.trim();if(v){db.pantry.push(v);save()}};document.querySelectorAll(".pantryDel").forEach(b=>b.onclick=()=>{db.pantry.splice(+b.dataset.pi,1);save()});
 if($("#skip"))$("#skip").onclick=render;if($("#saveIdea"))$("#saveIdea").onclick=e=>{let n=e.currentTarget.dataset.name;if(n&&!n.startsWith("Je hebt")){db.recipes.push({id:id(),name:n,servings:4,ingredients:[],instructions:"",image:""});save()}};
 if($("#savePrefs"))$("#savePrefs").onclick=()=>{db.prefs.days=+$("#pd").value;db.prefs.servings=+$("#ps").value;db.prefs.forbidden=$("#pf").value.split(",").map(x=>x.trim()).filter(Boolean);save()};
 if($("#backup"))$("#backup").onclick=backup;if($("#restore"))$("#restore").onchange=restore;if($("#share"))$("#share").onclick=sharePlan;if($("#shareShop"))$("#shareShop").onclick=shareShop;
 if($("#importRecipe"))$("#importRecipe").onclick=()=>$("#restore").click();
}
function manualPlan(){let days=Math.max(1,Math.min(14,+$("#days").value||5)),serv=Math.max(1,+$("#serv").value||4);if(!db.recipes.length)return alert("Voeg eerst recepten toe.");let out=[];for(let i=0;i<days;i++){let names=db.recipes.map((r,j)=>`${j+1}. ${r.name}`).join("\n");let c=prompt(`${i+1}/${days} — kies receptnummer:\n${names}`);if(c===null)return;let r=db.recipes[+c-1];if(!r){i--;continue}let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+i);out.push({date:d.toISOString().slice(0,10),recipeId:r.id,servings:serv})}db.plan=out;db.prefs.days=days;db.prefs.servings=serv;save()}
function editRecipe(rid){let r=db.recipes.find(x=>x.id===rid)||{id:id(),name:"",servings:4,ingredients:[],instructions:"",image:""};let name=prompt("Naam recept",r.name);if(name===null)return;let servings=+(prompt("Aantal personen",r.servings)||4);let raw=prompt("Ingrediënten — één per regel: hoeveelheid | eenheid | naam",r.ingredients.map(x=>`${x.quantity} | ${x.unit} | ${x.name}`).join("\n"))??"";let instructions=prompt("Bereidingswijze",r.instructions)??"";r.name=name.trim();r.servings=servings;r.instructions=instructions;r.ingredients=raw.split("\n").filter(Boolean).map(l=>{let [q,u,...n]=l.split("|").map(x=>x.trim());return {quantity:+String(q).replace(",","." )||0,unit:u||"",name:n.join(" | ")||u||q}});if(!rid)db.recipes.push(r);save()}
function planText(){return db.plan.sort((a,b)=>a.date.localeCompare(b.date)).map(p=>{let r=db.recipes.find(x=>x.id===p.recipeId);if(!r)return"";let f=p.servings/(r.servings||1);return `${nl(p.date).toUpperCase()}\n${r.name} — ${p.servings} personen\n\nINGREDIËNTEN\n${r.ingredients.map(x=>`• ${qty(x.quantity*f)} ${x.unit} ${x.name}`).join("\n")}\n\nBEREIDING\n${r.instructions}`}).join("\n\n━━━━━━━━━━━━\n\n")}
async function shareText(title,text){if(navigator.share)try{await navigator.share({title,text})}catch{}else{await navigator.clipboard.writeText(text);alert("Gekopieerd.")}}
function sharePlan(){shareText("MealPlan",planText())}function shareShop(){shareText("Boodschappen",aggregate().map(x=>`• ${qty(x.q)} ${x.unit} ${x.name}`).join("\n"))}
function backup(){let blob=new Blob([JSON.stringify(db,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`MealPlan-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
function restore(e){let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{let x=JSON.parse(rd.result);if(!x.recipes||!x.plan)throw 0;db={...structuredClone(D),...x};save();alert("Back-up geïmporteerd.")}catch{alert("Dit is geen geldige MealPlan-back-up.")}};rd.readAsText(f)}
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");
render();
